export default {
  loading: false,
  error: null,
  doctors: {
    byId: {
      'FJEIWYS': {
        id: 'FJEIWYS',
        name: 'Dr. Bhushan Goyal',
        avatar: require('../images/male-avatar.jpg'),
        speciality: 'Psychiatrist',
        phone: '9800100200',
        clinic: 'Goyal Clinic',
        location: 'Shivaji Chowk',
        rating: 98,
        charges: 350,
        reviews: 200,
      },
      'JFIWIFR': {
        id: 'JFIWIFR',
        name: 'Dr. Karuna Soni',
        avatar: require('../images/female-avatar.jpg'),
        speciality: 'Dermatologist',
        phone: '9800100200',
        clinic: 'SkinEthic Skin Clinic',
        location: 'Viman Nagar',
        rating: 100,
        charges: 500,
        reviews: 1000,
      },
      'KJFIWOP': {
        id: 'KJFIWOP',
        name: 'Dr. Rohan Sharma',
        avatar: require('../images/male-avatar.jpg'),
        speciality: 'Cardiologist',
        phone: '9800100200',
        clinic: 'Sanjeevani Hospital',
        location: 'Viman Nagar',
        rating: 80,
        charges: 500,
        reviews: 200,
      },
      'CDJQUDTF': {
        id: 'CDJQUDTF',
        name: 'Dr. Archana Singh',
        avatar: require('../images/female-avatar.jpg'),
        speciality: 'Neurologist',
        phone: '9800100200',
        clinic: 'Sanjeevani Hospital',
        location: 'Shivaji Chowk',
        rating: 75,
        charges: 500,
        reviews: 50,
      },
      'IWQHFICHF': {
        id: 'IWQHFICHF',
        name: 'Dr. Varun Chaturvedi',
        avatar: require('../images/male-avatar.jpg'),
        speciality: 'Urologist',
        phone: '9800100200',
        clinic: 'Sanjeevani Hospital',
        location: 'M. G. Road',
        rating: 85,
        charges: 500,
        reviews: 50,
      },
    },
    allIds: ['FJEIWYS', 'JFIWIFR', 'KJFIWOP', 'CDJQUDTF', 'IWQHFICHF']
  }
}